### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by annie-uchiha**
Initial setup complete - waiting for comments and suggestions

### CODE REVIEW

**Comment by innatssss** [comment]
Everything looks great just this bug with header
Screenshot 2024-04-19 at 10 27 25

**Comment by annie-uchiha** [comment]
ready for another review :)

**Comment by innatssss** [comment]
Screenshot 2024-04-20 at 19 08 57
Screenshot 2024-04-20 at 19 09 08

the same, works only on my 50% zoom out

**Comment by annie-uchiha** [comment]
I made some adjustments and added the jQuery just haven't linked it - I guess whoever decides to use it will link it in their page. About the navbar I don't see this bug even when I resize the screen. It appears once the screen is smaller than 800px.

**Review by innatssss — APPROVED** [review]
Thank you; everything looks great!

**Comment by elishab-dev** [comment]
зображення

is this how it's supposed to look at 100% view?

**Review by elishab-dev — APPROVED** [review]

**Pull request merged**
